In [19]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

def linear_regression(X1, y, learning_rate=0.01, num_iters=1000):
    X = np.c_[np.ones(len(X1)), X1]
    theta = np.zeros(X.shape[1]).reshape(-1,1)
    for _ in range(num_iters):
        predictions = (X).dot(theta).reshape(-1, 1)
        errors = (predictions - y).reshape(-1,1)
        theta -= learning_rate * (1 / len(X1)) * X.T.dot(errors)

    return theta


In [ ]:
data = pd.read_csv('50_Startups.csv',header=None)
data.head()


0               1                2           3          4
0  R&D Spend  Administration  Marketing Spend       State     Profit
1   165349.2        136897.8         471784.1    New York  192261.83
2   162597.7       151377.59        443898.53  California  191792.06
3  153441.51       101145.55        407934.54     Florida  191050.39
4  144372.41       118671.85        383199.62    New York  182901.99

In [21]:
X = (data.iloc[1:, :-2].values)
X1=X.astype(float)
scaler = StandardScaler()
print(X1)

[[165349.2  136897.8  471784.1 ]
 [162597.7  151377.59 443898.53]
 [153441.51 101145.55 407934.54]
 [144372.41 118671.85 383199.62]
 [142107.34  91391.77 366168.42]
 [131876.9   99814.71 362861.36]
 [134615.46 147198.87 127716.82]
 [130298.13 145530.06 323876.68]
 [120542.52 148718.95 311613.29]
 [123334.88 108679.17 304981.62]
 [101913.08 110594.11 229160.95]
 [100671.96  91790.61 249744.55]
 [ 93863.75 127320.38 249839.44]
 [ 91992.39 135495.07 252664.93]
 [119943.24 156547.42 256512.92]
 [114523.61 122616.84 261776.23]
 [ 78013.11 121597.55 264346.06]
 [ 94657.16 145077.58 282574.31]
 [ 91749.16 114175.79 294919.57]
 [ 86419.7  153514.11      0.  ]
 [ 76253.86 113867.3  298664.47]
 [ 78389.47 153773.43 299737.29]
 [ 73994.56 122782.75 303319.26]
 [ 67532.53 105751.03 304768.73]
 [ 77044.01  99281.34 140574.81]
 [ 64664.71 139553.16 137962.62]
 [ 75328.87 144135.98 134050.07]
 [ 72107.6  127864.55 353183.81]
 [ 66051.52 182645.56 118148.2 ]
 [ 65605.48 153032.06 107138.38]
 [ 61994.4

In [22]:
y = (data.iloc[1:,-1].values).reshape(-1,1)
print(y)

[['192261.83']
 ['191792.06']
 ['191050.39']
 ['182901.99']
 ['166187.94']
 ['156991.12']
 ['156122.51']
 ['155752.6']
 ['152211.77']
 ['149759.96']
 ['146121.95']
 ['144259.4']
 ['141585.52']
 ['134307.35']
 ['132602.65']
 ['129917.04']
 ['126992.93']
 ['125370.37']
 ['124266.9']
 ['122776.86']
 ['118474.03']
 ['111313.02']
 ['110352.25']
 ['108733.99']
 ['108552.04']
 ['107404.34']
 ['105733.54']
 ['105008.31']
 ['103282.38']
 ['101004.64']
 ['99937.59']
 ['97483.56']
 ['97427.84']
 ['96778.92']
 ['96712.8']
 ['96479.51']
 ['90708.19']
 ['89949.14']
 ['81229.06']
 ['81005.76']
 ['78239.91']
 ['77798.83']
 ['71498.49']
 ['69758.98']
 ['65200.33']
 ['64926.08']
 ['49490.75']
 ['42559.73']
 ['35673.41']
 ['14681.4']]


In [23]:
X1_Scaled = scaler.fit_transform(X1)
Y1_Scaled = scaler.fit_transform(y)
theta = linear_regression(X1_Scaled, Y1_Scaled)
new_data = np.array([165349.2,136897.8,471784.1]).reshape(-1,1)
new_Scaled = scaler.fit_transform(new_data)
prediction =np.dot(np.append(1, new_Scaled), theta)
prediction=prediction.reshape(-1,1)
pre=scaler.inverse_transform(prediction)
print(f"Predicted value: {pre}")

Predicted value: [[203866.53076613]]
